#!/bin/bash

IFACE_NUM=$(echo $dev | cut -c 4-)
DEV=tun${IFACE_NUM}

NETNS_NAME=$1
VPN_PROVIDER=${1%%:*}
DEVNAME=$2
TUN_MTU=$3
LINK_MTU=$4
LOCAL_IP=$5
REMOTE_IP=$6
STATE=$7
# cmd tun_dev tun_mtu link_mtu ifconfig_local_ip ifconfig_remote_ip [ init | restart ]

case $script_type in
    up)
        ip netns add ${NETNS_NAME}
        ip netns exec ${NETNS_NAME} ip link set dev lo up
        ip link set dev "${DEV}" up netns ${NETNS_NAME} mtu "$TUN_MTU"
        ip netns exec ${NETNS_NAME} ip addr add dev "${DEV}" "$LOCAL_IP/${ifconfig_netmask:-30}" ${ifconfig_broadcast:+broadcast "$ifconfig_broadcast"}
        if [ -h /etc/netns/${NETNS_NAME} ]; then
            rm -f /etc/netns/${NETNS_NAME}
        fi
        
        # Set the per-provider resolv.conf to be active for this netns
        ln -s ${VPN_PROVIDER} /etc/netns/${NETNS_NAME}
        
        if [ -n "$ifconfig_ipv6_local" ]; then
            ip netns exec ${NETNS_NAME} ip addr add dev "${DEV}" "$ifconfig_ipv6_local"/112
        fi
    ;;
    route-up)
        ip netns exec ${NETNS_NAME} ip route add default via "$route_vpn_gateway"
        if [ -n "$ifconfig_ipv6_remote" ]; then
            ip netns exec ${NETNS_NAME} ip route add default via "$ifconfig_ipv6_remote"
        fi
    ;;
    down)
        ip netns delete ${NETNS_NAME}
    ;;
esac
